# Generated by Django 4.2.10 on 2024-03-04 15:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SForm',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('label', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'S-Form',
                'verbose_name_plural': 'S-Forms',
            },
        ),
        migrations.CreateModel(
            name='SFormRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-z\\_]*$', 'Only lowercase alphanumeric characters and underscore are allowed.')])),
                ('fieldtype', models.CharField(choices=[('text', 'Text'), ('email', 'E-mail'), ('password', 'Password'), ('number', 'Number'), ('textarea', 'Textarea'), ('checkbox', 'Checkbox'), ('multicheckbox', 'Multicheckbox'), ('radio', 'Radio'), ('choice', 'Choice'), ('hidden', 'Hidden'), ('label', 'Label')], max_length=15)),
                ('required', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=150, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=150, null=True)),
                ('default', models.CharField(blank=True, max_length=150, null=True)),
                ('values', models.TextField(blank=True, default='', help_text='List of Value or Value:Label, each value on a new line ')),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sforms.sform')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('form', 'name')},
            },
        ),
    ]
