# Generated by Django 4.2.10 on 2024-03-08 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFormResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(default=dict)),
                ('values', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sformrow',
            options={'ordering': ('order',), 'verbose_name': "S-Form's row"},
        ),
        migrations.AlterField(
            model_name='sformrow',
            name='fieldtype',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'E-mail'), ('password', 'Password'), ('number', 'Number'), ('textarea', 'Textarea'), ('checkbox', 'Checkbox'), ('multicheckbox', 'Multicheckbox'), ('radio', 'Radio'), ('choice', 'Choice'), ('hidden', 'Hidden'), ('label', 'Label'), ('attach', 'Attachment')], max_length=15),
        ),
        migrations.CreateModel(
            name='SFormResultAttach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('value', models.FileField(upload_to='')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sforms.sformresult')),
            ],
        ),
    ]
